a<-read.table("household_power_consumption.txt", sep = ";",header = TRUE)
library(dplyr)
b<-filter(a, Date=="1/2/2007" | Date=="2/2/2007")
glo<-as.numeric(paste(b[,3]))
c<-paste(b[,1],b[,2])
d<-strptime(c,format = "%d/%m/%Y %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfcol=c(2,2))
plot(d,glo, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
sm1<-as.numeric(paste(b[,7]))
sm2<-as.numeric(paste(b[,8]))
sm3<-as.numeric(paste(b[,9]))
plot(d,sm1, type = "l", ylab = "Energy Sub Meeting", xlab = "")
lines(d,sm2, type = "l", col="Red")
lines(d,sm3, type = "l", col="Blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"), bty="n",cex=0.8)

e<-as.numeric(paste(b[,5]))
f<-as.numeric(paste(b[,4]))
plot(d,e, type = "l", xlab = "datetime",ylab = "Voltage")
plot(d,f, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
dev.off()