a<-read.table("household_power_consumption.txt", sep = ";",header = TRUE)
library(dplyr)
b<-filter(a, Date=="1/2/2007" | Date=="2/2/2007")
glo<-as.numeric(paste(b[,3]))
c<-paste(b[,1],b[,2])
d<-strptime(c,format = "%d/%m/%Y %H:%M:%S")
png("plot2.png", width=480, height=480)
plot(d,glo, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()
